name: Deploy OCPP-SERVER

on:
  push:
    branches: [ "master" ] 
  workflow_dispatch:

env:
  DST: /var/lib/openhab/ocpp-server
  FILE: central_system.py
  SRV: ocpp

jobs:
  copy_code:
    name: "kopijavimas i hera"
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - run: cp * $DST
    - run: chown openhab:openhab $DST/*
