name: Deploy OCPP-SERVER

on:
  push:
    branches: [ "master" ] 
  workflow_dispatch:

env:
  DST: /var/lib/openhab/ocpp-server
  FILE: central_system.py
  SRV: ocpp

jobs:
  deploy:
    name: "Perkelimasi i hera"
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - run: systemctl stop $SRV

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "$DST/$FILE"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: mv $DST $DST/$FILE1
    
    - run: cp * $DST
    - run: chown openhab:openhab $DST/*

    - run: source $DST/venv/bin/activate
    - run: pip install requirements.txt

    - run: systemctl start $SRV
    
